services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'XtreamDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
      - appnetwork
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
networks:
  appnetwork:
    driver: bridge